# This rule is not used by the project cronjob-guardian itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over guardian.illenium.net.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cronjob-guardian
    app.kubernetes.io/managed-by: kustomize
  name: alertchannel-admin-role
rules:
- apiGroups:
  - guardian.illenium.net
  resources:
  - alertchannels
  verbs:
  - '*'
- apiGroups:
  - guardian.illenium.net
  resources:
  - alertchannels/status
  verbs:
  - get
