# This rule is not used by the project cronjob-guardian itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the guardian.illenium.net.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cronjob-guardian
    app.kubernetes.io/managed-by: kustomize
  name: cronjobmonitor-editor-role
rules:
- apiGroups:
  - guardian.illenium.net
  resources:
  - cronjobmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - guardian.illenium.net
  resources:
  - cronjobmonitors/status
  verbs:
  - get
