apiVersion: guardian.illenium.net/v1alpha1
kind: GuardianConfig
metadata:
  labels:
    app.kubernetes.io/name: cronjob-guardian
    app.kubernetes.io/managed-by: kustomize
  name: guardianconfig-sample
spec:
  # TODO(user): Add fields here
