apiVersion: guardian.illenium.net/v1alpha1
kind: AlertChannel
metadata:
  labels:
    app.kubernetes.io/name: cronjob-guardian
    app.kubernetes.io/managed-by: kustomize
  name: alertchannel-sample
  namespace: default
spec:
  type: webhook
  webhook:
    urlSecretRef:
      name: sample-webhook-secret
      namespace: default
      key: url
