## Append samples of your project ##
resources:
- guardian_v1alpha1_cronjobmonitor.yaml
- guardian_v1alpha1_alertchannel.yaml
- guardian_v1alpha1_guardianconfig.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
